apiVersion: v1
kind: ConfigMap
metadata: 
 name:  {{ include "mychart.fullname" . }}-config
data:
 DB_HOST: {{ .Values.externalDatabase.dbhost | quote }}
 DB_NAME:  {{ .Values.externalDatabase.dbname | quote }}
 DB_PORT:  {{ .Values.externalDatabase.dbport | quote }}

