apiVersion: v1
kind: Secret
metadata:
 name: {{ include "mychart.fullname" . }}-secret

type: Opaque
data:
 DB_USER: {{ .Values.externalDatabase.dbuser | b64enc | quote }}
 DB_PASS: {{ .Values.externalDatabase.dbpass | b64enc | quote }}
